Vagrant.configure(2) do |config|
    config.vm.box = "generic/ubuntu2204"
    config.vm.define "dmercadiS" do |control|
        control.vm.hostname = "dmercadiS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "dmercadiS"]
            v.memory = 1024
            v.cpus = 1
        end
        config.vm.provision "shell", inline: <<-SHELL
            export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --tls-san serverS --node-ip 192.168.56.110 --bind-address=192.168.56.110 --advertise-address=192.168.56.110 "
            curl -sfL https://get.k3s.io | sh -
            sudo cat /var/lib/rancher/k3s/server/token >> /vagrant/token.env
            sudo ip link add eth1 type dummy && sudo ip addr add 192.168.56.110/24 dev eth1 && sudo ip link set eth1 up
        SHELL
    end
    config.vm.define "dmercadiSW" do |control|
        control.vm.hostname = "dmercadiSW"
        control.vm.network "private_network", ip: "192.168.56.111"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "dmercadiSW"]
            v.memory = 1024
            v.cpus = 1
        end
        config.vm.provision "shell", inline: <<-SHELL
            export INSTALL_K3S_EXEC="agent --server https://192.168.56.110:6443 -t $(cat /vagrant/token.env) --node-ip=192.168.56.111"
            curl -sfL https://get.k3s.io | sh -
            sudo ip link add eth1 type dummy && sudo ip addr add 192.168.56.111/24 dev eth1 && sudo ip link set eth1 up
        SHELL
    end
end