Vagrant.configure(2) do |config|
    config.vm.box = "generic/alpine318"
    config.vm.define "dmercadiS" do |control|
        control.vm.hostname = "dmercadiS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "dmercadiS"]
            v.memory = 1024
            v.cpus = 1
        end
        config.vm.provision "shell", inline: <<-SHELL
            curl -sfL https://get.k3s.io | sh -
        SHELL
    end
    config.vm.define "dmercadiSW" do |control|
        control.vm.hostname = "dmercadiSW"
        control.vm.network "private_network", ip: "192.168.56.111"
        control.vm.provider "virtualbox" do |v|
            v.customize ["modifyvm", :id, "--name", "dmercadiSW"]
            v.memory = 1024
            v.cpus = 1
        end
        config.vm.provision "shell", inline: <<-SHELL
            sleep 30
            TOKEN=$(ssh -o StrictHostKeyChecking=no vagrant@192.168.56.110 "sudo cat /var/lib/rancher/k3s/server/node-token")
            curl -sfL https://get.k3s.io | K3S_URL=https://192.168.56.110:6443 K3S_TOKEN=$TOKEN sh -
        SHELL
    end
end