Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu1804"
  config.vm.define "dmercadiS" do |server|
    server.vm.hostname = "dmercadiS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "libvirt" do |v|
        v.memory = 1024
        v.cpus = 1
    end
    server.vm.provision "shell", inline: <<-SHELL
        sudo apt update && sudo apt upgrade -y
        sudo ufw disable
        export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --tls-san localhost --bind-address=0.0.0.0"
        sudo curl -sfL https://get.k3s.io | sh -
        k3s kubectl	apply -f deployments.yaml
        k3s kubectl	apply -f services.yaml
        k3s kubectl	apply -f ingresses.yaml
    SHELL
  end
end