Vagrant.configure(2) do |config|
    config.vm.box = "generic/ubuntu1804"
    config.vm.synced_folder ".","/vagrant", type:"nfs", nfs_version:4
    config.vm.define "dmercadiS" do |control|
        control.vm.hostname = "dmercadiS"
        control.vm.network "private_network", ip: "192.168.56.110"
        control.vm.provider "libvirt" do |v|
            v.memory = 1024
            v.cpus = 1
        end
        control.vm.provision "shell", inline: <<-SHELL
            sudo apt update && sudo apt upgrade -y
            sudo ufw disable
            export INSTALL_K3S_EXEC="--write-kubeconfig-mode=644 --tls-san serverS --node-ip 192.168.56.110 --bind-address=192.168.56.110 --advertise-address=192.168.56.110 "
            curl -sfL https://get.k3s.io | sh -
            sudo cat /var/lib/rancher/k3s/server/token > /vagrant/token.env && echo "Token saved!"
        SHELL
    end
    config.vm.define "dmercadiSW" do |control|
        control.vm.hostname = "dmercadiSW"
        control.vm.network "private_network", ip: "192.168.56.111"
        control.vm.provider "libvirt" do |v|
            v.memory = 1024
            v.cpus = 1
        end
        control.vm.provision "shell", inline: <<-SHELL
            sudo apt update && sudo apt upgrade -y
            sudo ufw disable
            file=/vagrant/token.env
            while [ ! -f "$file" ]; do sleep 4; echo "Waiting for token..."; done
            export INSTALL_K3S_EXEC="agent --server https://192.168.56.110:6443 -t $(cat /vagrant/token.env) --node-ip=192.168.56.111"
            rm -f /vagrant/token.env
            curl -sfL https://get.k3s.io | sh -
        SHELL
    end
end